// ===========================================
// Mock Product Catalog — Phase 3 Demonstration Data
// ===========================================
// IMPORTANT: All products below are realistic demonstration records
// strictly tagged with source: 'mock'. They do NOT represent live
// inventory, real-time availability, or confirmed commercial pricing
// from the Dwell Mart production store.
// ===========================================

import { Product, CategoryInfo } from './types';

export const MOCK_CATEGORIES_DATA: CategoryInfo[] = [
  {
    id: 'cat-fresh-veg',
    name: 'Fresh Vegetables',
    slug: 'fresh-vegetables',
    description: 'Farm-fresh bulk vegetables for commercial kitchens and retail',
    productCount: 4,
    subcategories: ['Root Vegetables', 'Leafy Greens', 'Gourds & Squash', 'Exotics'],
  },
  {
    id: 'cat-staples-grains',
    name: 'Staples & Grains',
    slug: 'staples-grains',
    description: 'Premium quality raw grains, rice varieties, and wholesale cereals',
    productCount: 4,
    subcategories: ['Basmati Rice', 'Sona Masoori', 'Millets & Quinoa', 'Raw Grains'],
  },
  {
    id: 'cat-flours-atta',
    name: 'Flours & Atta',
    slug: 'flours-atta',
    description: 'Whole wheat chakki atta, specialty flours, and besan in commercial packs',
    productCount: 3,
    subcategories: ['Wheat Atta', 'Gram Flour (Besan)', 'Multigrain Flours'],
  },
  {
    id: 'cat-pulses-lentils',
    name: 'Pulses & Lentils',
    slug: 'pulses-lentils',
    description: 'Unpolished and polished dals, beans, and wholesale legumes',
    productCount: 4,
    subcategories: ['Toor Dal', 'Moong Dal', 'Urad & Chana', 'Rajma & Chhole'],
  },
  {
    id: 'cat-cooking-oils',
    name: 'Cooking Oils & Ghee',
    slug: 'cooking-oils-ghee',
    description: 'Mustard oil, sunflower oil, refined blends, and pure desi ghee tins',
    productCount: 3,
    subcategories: ['Desi Ghee', 'Mustard Oil', 'Refined & Sunflower Oil'],
  },
  {
    id: 'cat-spices-masalas',
    name: 'Spices & Masalas',
    slug: 'spices-masalas',
    description: 'Whole spices, ground aromatic masalas, and blended seasonings',
    productCount: 3,
    subcategories: ['Ground Spices', 'Whole Spices', 'Blended Masalas'],
  },
  {
    id: 'cat-packaged-foods',
    name: 'Packaged & Instant Foods',
    slug: 'packaged-instant-foods',
    description: 'Instant noodles, snacks, pasta, and ready-to-cook wholesale cartons',
    productCount: 3,
    subcategories: ['Noodles & Pasta', 'Namkeen & Snacks', 'Sauces & Condiments'],
  },
  {
    id: 'cat-dairy',
    name: 'Dairy',
    slug: 'dairy',
    description: 'Commercial paneer blocks, butter tubs, long-life milk, and cheese',
    productCount: 3,
    subcategories: ['Butter & Cheese', 'Paneer', 'UHT Milk'],
  },
  {
    id: 'cat-bakery',
    name: 'Bakery',
    slug: 'bakery',
    description: 'Bulk sandwich bread loaves, rusks, biscuits, and bakery supplies',
    productCount: 3,
    subcategories: ['Breads & Buns', 'Cookies & Biscuits', 'Rusk & Toast'],
  },
  {
    id: 'cat-inverters',
    name: 'Inverters',
    slug: 'inverters',
    description: 'Pure sine wave power backup inverters, hybrid solar inverters, and UPS systems',
    productCount: 4,
    subcategories: ['Pure Sine Wave Inverters', 'Heavy-Duty Commercial UPS', 'Solar Hybrid Inverters'],
  },
  {
    id: 'cat-electrical-acc',
    name: 'Electrical Accessories',
    slug: 'electrical-accessories',
    description: 'Modular switches, circuit breakers, copper wiring, and distribution boxes',
    productCount: 3,
    subcategories: ['Modular Switches', 'Copper Wire Bundles', 'MCB & Isolators'],
  },
  {
    id: 'cat-bikes-scooters',
    name: 'Bikes and Scooters',
    slug: 'bikes-and-scooters',
    description: 'Commercial cargo scooters, commuter two-wheelers, and accessories',
    productCount: 3,
    subcategories: ['Commuter Scooters', 'Cargo Delivery Two-Wheelers', 'Utility Bikes'],
  },
  {
    id: 'cat-electric-scooters',
    name: 'Electric Scooters',
    slug: 'electric-scooters',
    description: 'Lithium-ion powered EV scooters, commercial fleet delivery EVs',
    productCount: 3,
    subcategories: ['Fleet Delivery EV', 'High-Speed EV Scooters', 'Low-Speed Commuter EV'],
  },
  {
    id: 'cat-cycles',
    name: 'Cycles',
    slug: 'cycles',
    description: 'Heavy-duty delivery roadsters, mountain cycles, and hybrid city bicycles',
    productCount: 3,
    subcategories: ['Commercial Cargo Cycles', 'Mountain Terrain Bicycles', 'City Commuter Cycles'],
  },
  {
    id: 'cat-home-general',
    name: 'Home and General Products',
    slug: 'home-general-products',
    description: 'Ergonomic office seating, stainless steel cookware, and home storage racks',
    productCount: 4,
    subcategories: ['Furniture & Seating', 'Cookware Sets', 'Storage & Shelving', 'Decor'],
  },
];

export const MOCK_PRODUCTS_DATA: Product[] = [
  // ── Fresh Vegetables ──
  {
    id: 'prod-veg-001',
    name: 'Farm Fresh Red Onions — Wholesale Sack',
    slug: 'farm-fresh-red-onions-wholesale-sack',
    description: 'Medium-to-large sorted Nashik red onions with firm skins and long shelf life. Ideal for hotels, caterers, and bulk grocery supply.',
    category: 'Fresh Vegetables',
    subcategory: 'Root Vegetables',
    brand: 'Kisan Fresh Direct',
    price: 1350,
    wholesalePrice: 1100,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 420,
    minimumOrderQuantity: 5,
    tags: ['onion', 'vegetables', 'fresh', 'nashik', 'bulk vegetable', 'pyaz'],
    source: 'mock',
    lastUpdated: '2026-03-01',
    unit: '50 kg sack',
  },
  {
    id: 'prod-veg-002',
    name: 'Cold-Storage Grade Potatoes (Jyoti Variety)',
    slug: 'cold-storage-potatoes-jyoti',
    description: 'Dry, unwashed mature potatoes graded for commercial fryers and daily cooking. Low sugar content reduces browning during frying.',
    category: 'Fresh Vegetables',
    subcategory: 'Root Vegetables',
    brand: 'Kisan Fresh Direct',
    price: 950,
    wholesalePrice: 820,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 650,
    minimumOrderQuantity: 10,
    tags: ['potato', 'aloo', 'vegetables', 'bulk potato', 'fries'],
    source: 'mock',
    unit: '50 kg sack',
  },
  {
    id: 'prod-veg-003',
    name: 'Hydroponic English Cucumbers',
    slug: 'hydroponic-english-cucumbers',
    description: 'Crisp, seedless hydroponic cucumbers individually shrink-wrapped for maximum freshness. Preferred by salad bars and fine dining.',
    category: 'Fresh Vegetables',
    subcategory: 'Exotics',
    brand: 'GreenOasis Farms',
    price: 750,
    wholesalePrice: 620,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 80,
    minimumOrderQuantity: 3,
    tags: ['cucumber', 'kheera', 'hydroponic', 'salad', 'exotic'],
    source: 'mock',
    unit: '10 kg crate',
  },
  {
    id: 'prod-veg-004',
    name: 'Desi Roma Tomatoes (Firm Red)',
    slug: 'desi-roma-tomatoes-firm-red',
    description: 'Plump, thick-skinned tomatoes with balanced acidity, handpicked for sauce preparation, gravies, and restaurant supply.',
    category: 'Fresh Vegetables',
    subcategory: 'Gourds & Squash',
    brand: 'Kisan Fresh Direct',
    price: 480,
    wholesalePrice: 390,
    currency: 'INR',
    stockStatus: 'low_stock',
    availableQuantity: 18,
    minimumOrderQuantity: 4,
    tags: ['tomato', 'tamatar', 'vegetables', 'fresh', 'gravy'],
    source: 'mock',
    unit: '25 kg crate',
  },

  // ── Staples & Grains ──
  {
    id: 'prod-grain-001',
    name: 'India Gate Classic Basmati Rice (Aged 2 Years)',
    slug: 'india-gate-classic-basmati-rice-25kg',
    description: 'Extra long grain aged aromatic Basmati rice. Slender grains elongate up to twice their original size when cooked. Superb for Biryanis and Pulao.',
    category: 'Staples & Grains',
    subcategory: 'Basmati Rice',
    brand: 'India Gate',
    price: 3450,
    wholesalePrice: 2950,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 280,
    minimumOrderQuantity: 3,
    tags: ['rice', 'basmati', 'chawal', 'biryani', 'aged rice', 'grains'],
    source: 'mock',
    unit: '25 kg bag',
  },
  {
    id: 'prod-grain-002',
    name: 'Fortune Everyday Basmati Rice',
    slug: 'fortune-everyday-basmati-rice-10kg',
    description: 'Fluffy, non-sticky long grains with mild natural aroma suitable for daily household cooking, catering menus, and mess facilities.',
    category: 'Staples & Grains',
    subcategory: 'Basmati Rice',
    brand: 'Fortune',
    price: 890,
    wholesalePrice: 740,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 340,
    minimumOrderQuantity: 5,
    tags: ['rice', 'fortune', 'everyday rice', 'chawal', '10kg'],
    source: 'mock',
    unit: '10 kg bag',
  },
  {
    id: 'prod-grain-003',
    name: 'Royal Sona Masoori Raw Rice (Silky Sortex)',
    slug: 'royal-sona-masoori-raw-rice-25kg',
    description: 'Medium grain lightweight aromatic rice cultivated in Andhra river basins. Easy to digest and preferred for daily South Indian meals.',
    category: 'Staples & Grains',
    subcategory: 'Sona Masoori',
    brand: 'Dwell Select Staples',
    price: 1650,
    wholesalePrice: 1420,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 190,
    minimumOrderQuantity: 4,
    tags: ['rice', 'sona masoori', 'south indian', 'chawal', 'staples'],
    source: 'mock',
    unit: '25 kg bag',
  },
  {
    id: 'prod-grain-004',
    name: 'Organic Barnyard & Foxtail Millet Combo',
    slug: 'organic-millet-combo-pack',
    description: 'Gluten-free unpolished ancient millets rich in dietary fiber and micronutrients. Certified pesticide-free bulk packing.',
    category: 'Staples & Grains',
    subcategory: 'Millets & Quinoa',
    brand: 'NutriHarvest',
    price: 1250,
    wholesalePrice: 990,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 95,
    minimumOrderQuantity: 2,
    tags: ['millet', 'foxtail', 'gluten free', 'healthy grain', 'organic'],
    source: 'mock',
    unit: '10 kg box',
  },

  // ── Flours & Atta ──
  {
    id: 'prod-atta-001',
    name: 'Aashirvaad Shudh Chakki Atta (100% Whole Wheat)',
    slug: 'aashirvaad-shudh-chakki-atta-10kg',
    description: 'Traditional chakki-milled whole wheat flour that retains natural dietary fibers. Makes soft, fluffy rotis that stay tender for hours.',
    category: 'Flours & Atta',
    subcategory: 'Wheat Atta',
    brand: 'Aashirvaad',
    price: 460,
    wholesalePrice: 395,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 520,
    minimumOrderQuantity: 10,
    tags: ['atta', 'aashirvaad', 'wheat flour', 'roti', 'gehu'],
    source: 'mock',
    unit: '10 kg pack',
  },
  {
    id: 'prod-atta-002',
    name: 'Fortune Superfood Multigrain Atta',
    slug: 'fortune-superfood-multigrain-atta-5kg',
    description: 'Enriched blend of wheat, soya, chana, oat, maize, and psyllium husk providing wholesome protein and sustained digestive wellness.',
    category: 'Flours & Atta',
    subcategory: 'Multigrain Flours',
    brand: 'Fortune',
    price: 290,
    wholesalePrice: 245,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 210,
    minimumOrderQuantity: 8,
    tags: ['multigrain', 'atta', 'fortune', 'dietary fiber', 'wheat'],
    source: 'mock',
    unit: '5 kg pack',
  },
  {
    id: 'prod-atta-003',
    name: 'Tata Sampann Fine Pure Chana Besan',
    slug: 'tata-sampann-fine-chana-besan-15kg',
    description: '100% unadulterated Bengal gram flour milled to a micro-fine texture. Ideal for laddoos, pakoras, dhoklas, and commercial snack production.',
    category: 'Flours & Atta',
    subcategory: 'Gram Flour (Besan)',
    brand: 'Tata Sampann',
    price: 1780,
    wholesalePrice: 1520,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 130,
    minimumOrderQuantity: 2,
    tags: ['besan', 'gram flour', 'chana', 'tata sampann', 'pakora'],
    source: 'mock',
    unit: '15 kg bulk sack',
  },

  // ── Pulses & Lentils ──
  {
    id: 'prod-pulse-001',
    name: 'Tata Sampann Unpolished Toor Dal (Arhar)',
    slug: 'tata-sampann-unpolished-toor-dal-30kg',
    description: 'Premium laser-sorted unpolished Arhar dal without water, oil, or artificial marble powder polish. Cooks quickly with natural aroma.',
    category: 'Pulses & Lentils',
    subcategory: 'Toor Dal',
    brand: 'Tata Sampann',
    price: 4950,
    wholesalePrice: 4250,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 160,
    minimumOrderQuantity: 2,
    tags: ['toor dal', 'arhar', 'pulses', 'dal', 'unpolished', 'protein'],
    source: 'mock',
    unit: '30 kg sack',
  },
  {
    id: 'prod-pulse-002',
    name: 'NutriHarvest Dhuli Moong Dal (Yellow Split)',
    slug: 'nutriharvest-dhuli-moong-dal-25kg',
    description: 'Hygienically machine-cleaned yellow split lentils, high in easily digestible protein and recommended for convalescent and diet menus.',
    category: 'Pulses & Lentils',
    subcategory: 'Moong Dal',
    brand: 'NutriHarvest',
    price: 3300,
    wholesalePrice: 2820,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 140,
    minimumOrderQuantity: 3,
    tags: ['moong dal', 'yellow dal', 'pulses', 'lentils', 'light food'],
    source: 'mock',
    unit: '25 kg sack',
  },
  {
    id: 'prod-pulse-003',
    name: 'Chitra Red Rajma (Jammu Kidney Beans)',
    slug: 'chitra-red-rajma-jammu-25kg',
    description: 'Himalayan foothills grown speckled red kidney beans. Melts tenderly when slow-cooked, yielding a naturally thick rich gravy.',
    category: 'Pulses & Lentils',
    subcategory: 'Rajma & Chhole',
    brand: 'Dwell Select Staples',
    price: 3950,
    wholesalePrice: 3380,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 110,
    minimumOrderQuantity: 2,
    tags: ['rajma', 'kidney beans', 'jammu', 'pulses', 'chitra'],
    source: 'mock',
    unit: '25 kg sack',
  },
  {
    id: 'prod-pulse-004',
    name: 'Kabuli Chana Bold (12mm Jumbo Chickpeas)',
    slug: 'kabuli-chana-bold-12mm-25kg',
    description: 'Extra-large uniform size chickpeas favored by banquet chefs for Chhole Bhature and hummus spreads. High boil yield.',
    category: 'Pulses & Lentils',
    subcategory: 'Rajma & Chhole',
    brand: 'Dwell Select Staples',
    price: 3750,
    wholesalePrice: 3200,
    currency: 'INR',
    stockStatus: 'low_stock',
    availableQuantity: 15,
    minimumOrderQuantity: 2,
    tags: ['kabuli chana', 'chole', 'chickpeas', 'white chana', 'pulses'],
    source: 'mock',
    unit: '25 kg sack',
  },

  // ── Cooking Oils & Ghee ──
  {
    id: 'prod-oil-001',
    name: 'Fortune Sunlite Refined Sunflower Oil Tin',
    slug: 'fortune-sunlite-sunflower-oil-15l-tin',
    description: 'Enriched with Vitamin A and D, light and neutral flavored oil with a high smoke point. Resists breakdown during prolonged deep frying.',
    category: 'Cooking Oils & Ghee',
    subcategory: 'Refined & Sunflower Oil',
    brand: 'Fortune',
    price: 2150,
    wholesalePrice: 1880,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 310,
    minimumOrderQuantity: 4,
    tags: ['sunflower oil', 'fortune', 'refined oil', 'cooking oil', '15l tin'],
    source: 'mock',
    unit: '15 Liter Tin',
  },
  {
    id: 'prod-oil-002',
    name: 'Engine Brand Kachi Ghani Pure Mustard Oil Tin',
    slug: 'engine-kachi-ghani-mustard-oil-15l',
    description: 'Cold-pressed traditional mustard seed oil with signature strong pungency and natural antioxidants. Preferred for North and East Indian cuisine.',
    category: 'Cooking Oils & Ghee',
    subcategory: 'Mustard Oil',
    brand: 'Engine Brand',
    price: 2380,
    wholesalePrice: 2060,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 180,
    minimumOrderQuantity: 3,
    tags: ['mustard oil', 'sarson tel', 'kachi ghani', 'cooking oil', 'engine'],
    source: 'mock',
    unit: '15 Liter Tin',
  },
  {
    id: 'prod-oil-003',
    name: 'Amul Pure Desi Cow Ghee (Bulk Commercial Tin)',
    slug: 'amul-pure-desi-cow-ghee-15kg-tin',
    description: 'Granular (danedar) golden cow ghee prepared from fresh pasteurized cream. Rich traditional aroma essential for festive sweets and daily thalis.',
    category: 'Cooking Oils & Ghee',
    subcategory: 'Desi Ghee',
    brand: 'Amul',
    price: 9450,
    wholesalePrice: 8350,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 75,
    minimumOrderQuantity: 1,
    tags: ['ghee', 'amul', 'desi ghee', 'cow ghee', 'danedar', 'dairy'],
    source: 'mock',
    unit: '15 kg Tin',
  },

  // ── Spices & Masalas ──
  {
    id: 'prod-spice-001',
    name: 'MDH Deggi Mirch Powder (Bulk Master Carton)',
    slug: 'mdh-deggi-mirch-powder-master-carton',
    description: 'Famous blend of Kashmiri and red capsicum chillies providing brilliant red color without excessive pungency. Master carton contains 20 x 500g boxes.',
    category: 'Spices & Masalas',
    subcategory: 'Ground Spices',
    brand: 'MDH',
    price: 3600,
    wholesalePrice: 3080,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 90,
    minimumOrderQuantity: 2,
    tags: ['mirch', 'chilli powder', 'deggi mirch', 'mdh', 'spices', 'kashmiri'],
    source: 'mock',
    unit: '10 kg Master Carton',
  },
  {
    id: 'prod-spice-002',
    name: 'Catch Super Garam Masala Blend (Aromatic Formulation)',
    slug: 'catch-super-garam-masala-blend-5kg',
    description: 'Low-temperature ground spice concoction featuring green cardamom, cloves, cinnamon, mace, and black pepper for a fragrant culinary finish.',
    category: 'Spices & Masalas',
    subcategory: 'Blended Masalas',
    brand: 'Catch',
    price: 2850,
    wholesalePrice: 2420,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 65,
    minimumOrderQuantity: 2,
    tags: ['garam masala', 'catch', 'aromatic spices', 'masala blend'],
    source: 'mock',
    unit: '5 kg pail',
  },
  {
    id: 'prod-spice-003',
    name: 'Salem Special Bold Turmeric Fingers (Whole Haldi)',
    slug: 'salem-bold-turmeric-fingers-25kg',
    description: 'Export-grade Salem whole turmeric fingers with over 3.5% natural curcumin content. Free from lead chromate or polish.',
    category: 'Spices & Masalas',
    subcategory: 'Whole Spices',
    brand: 'Dwell Select Staples',
    price: 3900,
    wholesalePrice: 3350,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 85,
    minimumOrderQuantity: 2,
    tags: ['turmeric', 'haldi', 'curcumin', 'whole spice', 'salem'],
    source: 'mock',
    unit: '25 kg bag',
  },

  // ── Packaged & Instant Foods ──
  {
    id: 'prod-pkg-001',
    name: 'Maggi 2-Minute Masala Noodles (Catering Pack 96 units)',
    slug: 'maggi-masala-noodles-catering-case',
    description: 'Indias favorite instant masala noodles in a bulk master shipping case of 96 single-serve packs. Staple item for hostels, cafes, and pantries.',
    category: 'Packaged & Instant Foods',
    subcategory: 'Noodles & Pasta',
    brand: 'Nestle Maggi',
    price: 1344,
    wholesalePrice: 1140,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 320,
    minimumOrderQuantity: 5,
    tags: ['maggi', 'instant noodles', 'snack', 'nestle', 'wholesale case'],
    source: 'mock',
    unit: 'Case of 96 packs',
  },
  {
    id: 'prod-pkg-002',
    name: 'Haldirams Classic Bhujia Sev (5 kg Commercial Carton)',
    slug: 'haldirams-classic-bhujia-sev-5kg',
    description: 'Authentic Bikaneri moth dal bhujia spiced with pepper and cardamom. Crisp texture, packed in nitrogen-flushed food-grade foil liners.',
    category: 'Packaged & Instant Foods',
    subcategory: 'Namkeen & Snacks',
    brand: 'Haldirams',
    price: 1450,
    wholesalePrice: 1220,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 140,
    minimumOrderQuantity: 3,
    tags: ['bhujia', 'namkeen', 'haldirams', 'sev', 'snacks', 'bikaner'],
    source: 'mock',
    unit: '5 kg bulk box',
  },
  {
    id: 'prod-pkg-003',
    name: 'Kissan Fresh Tomato Ketchup Dispenser Pouch (5 kg)',
    slug: 'kissan-fresh-tomato-ketchup-5kg',
    description: 'Rich tomato ketchup with balanced sweet and tangy notes, packaged in heavy-gauge commercial dispenser pouches with pouring spout.',
    category: 'Packaged & Instant Foods',
    subcategory: 'Sauces & Condiments',
    brand: 'Kissan',
    price: 495,
    wholesalePrice: 410,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 210,
    minimumOrderQuantity: 6,
    tags: ['ketchup', 'tomato sauce', 'kissan', 'condiments', 'bulk sauce'],
    source: 'mock',
    unit: '5 kg spout pouch',
  },

  // ── Dairy ──
  {
    id: 'prod-dairy-001',
    name: 'Amul Malai Paneer Commercial Block (5 kg Cryovac Pack)',
    slug: 'amul-malai-paneer-5kg-block',
    description: 'Fresh pasteurized full-cream cottage cheese block vacuum-sealed to preserve soft texture and authentic dairy taste without crumbling.',
    category: 'Dairy',
    subcategory: 'Paneer',
    brand: 'Amul',
    price: 1850,
    wholesalePrice: 1610,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 110,
    minimumOrderQuantity: 2,
    tags: ['paneer', 'amul', 'dairy', 'fresh paneer', 'malai paneer'],
    source: 'mock',
    unit: '5 kg vacuum pack',
  },
  {
    id: 'prod-dairy-002',
    name: 'Amul Salted Table Butter (Bulk 5 kg Block)',
    slug: 'amul-table-butter-5kg-block',
    description: 'Classic yellow pasteurized salted butter block tailored for bakeries, restaurants, and confectioneries. 80% minimum milk fat.',
    category: 'Dairy',
    subcategory: 'Butter & Cheese',
    brand: 'Amul',
    price: 2750,
    wholesalePrice: 2420,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 85,
    minimumOrderQuantity: 2,
    tags: ['butter', 'amul', 'table butter', 'bakery', 'dairy'],
    source: 'mock',
    unit: '5 kg Block',
  },
  {
    id: 'prod-dairy-003',
    name: 'Amul Taaza Homogenised Toned UHT Milk (12 x 1L Pack)',
    slug: 'amul-taaza-uht-milk-carton-12l',
    description: 'Long-life aseptic UHT milk that stays fresh for 180 days at ambient temperatures without boiling. Perfect for pantry storage and beverages.',
    category: 'Dairy',
    subcategory: 'UHT Milk',
    brand: 'Amul',
    price: 840,
    wholesalePrice: 740,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 260,
    minimumOrderQuantity: 4,
    tags: ['milk', 'amul', 'taaza', 'uht milk', 'dairy', 'tetra pak'],
    source: 'mock',
    unit: 'Case of 12 x 1L packs',
  },

  // ── Bakery ──
  {
    id: 'prod-bakery-001',
    name: 'English Oven Jumbo White Sandwich Bread (Case of 12 Loaves)',
    slug: 'english-oven-jumbo-sandwich-bread-case',
    description: 'Square-cut, firm yet soft white bread loaves formulated for high-volume sandwich preparation and toasters. 800g per loaf.',
    category: 'Bakery',
    subcategory: 'Breads & Buns',
    brand: 'English Oven',
    price: 720,
    wholesalePrice: 590,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 120,
    minimumOrderQuantity: 3,
    tags: ['bread', 'sandwich bread', 'bakery', 'english oven', 'loaf'],
    source: 'mock',
    unit: 'Case of 12 loaves',
  },
  {
    id: 'prod-bakery-002',
    name: 'Britannia Toastea Premium Wheat Rusk (10 kg Bulk Box)',
    slug: 'britannia-toastea-wheat-rusk-10kg',
    description: 'Crispy, twice-baked golden rusks with subtle elaichi flavor. Packed in protective layers to minimize breakage during transit.',
    category: 'Bakery',
    subcategory: 'Rusk & Toast',
    brand: 'Britannia',
    price: 1350,
    wholesalePrice: 1120,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 95,
    minimumOrderQuantity: 2,
    tags: ['rusk', 'britannia', 'toastea', 'bakery', 'tea time', 'toast'],
    source: 'mock',
    unit: '10 kg bulk case',
  },
  {
    id: 'prod-bakery-003',
    name: 'Dwell Artisanal Butter Cookies Master Box',
    slug: 'dwell-artisanal-butter-cookies-6kg',
    description: 'Pure butter shortbread style cookies with almond flakes. Premium gift and hospitality tier for conference lounges and executive tea services.',
    category: 'Bakery',
    subcategory: 'Cookies & Biscuits',
    brand: 'Dwell Gourmet',
    price: 2100,
    wholesalePrice: 1720,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 50,
    minimumOrderQuantity: 2,
    tags: ['cookies', 'biscuits', 'butter cookies', 'bakery', 'confectionery'],
    source: 'mock',
    unit: '6 kg master box',
  },

  // ── Inverters ──
  {
    id: 'prod-inv-001',
    name: 'Luminous Zelio+ 1100 Pure Sine Wave Inverter',
    slug: 'luminous-zelio-plus-1100-pure-sine-wave-inverter',
    description: 'Smart 900VA / 12V pure sine wave home inverter with intuitive LED display indicating backup hours and charging status. Supports sensitive electronics and LED TVs.',
    category: 'Inverters',
    subcategory: 'Pure Sine Wave Inverters',
    brand: 'Luminous',
    price: 7499,
    wholesalePrice: 6299,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 85,
    minimumOrderQuantity: 2,
    tags: ['inverter', 'luminous', 'zelio', 'pure sine wave', 'home inverter', 'under 10000'],
    source: 'mock',
    unit: 'Unit',
  },
  {
    id: 'prod-inv-002',
    name: 'Microtek Luxe 1400 Smart Sine Wave Inverter',
    slug: 'microtek-luxe-1400-smart-sine-wave-inverter',
    description: '1100VA / 12V inverter with multi-stage smart battery charging and overload auto-reset. Runs up to 5 fans, 6 lights, and a desktop workstation reliably.',
    category: 'Inverters',
    subcategory: 'Pure Sine Wave Inverters',
    brand: 'Microtek',
    price: 8299,
    wholesalePrice: 6999,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 60,
    minimumOrderQuantity: 2,
    tags: ['inverter', 'microtek', 'sine wave', 'ups', 'power backup', 'under 10000'],
    source: 'mock',
    unit: 'Unit',
  },
  {
    id: 'prod-inv-003',
    name: 'Luminous Cruze 2.5kVA / 36V Commercial UPS',
    slug: 'luminous-cruze-2-5kva-36v-commercial-ups',
    description: 'Heavy duty commercial capacity inverter capable of powering deep freezers, dental chairs, laser printers, and small office server racks during power cuts.',
    category: 'Inverters',
    subcategory: 'Heavy-Duty Commercial UPS',
    brand: 'Luminous',
    price: 24500,
    wholesalePrice: 20900,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 25,
    minimumOrderQuantity: 1,
    tags: ['inverter', 'commercial ups', 'luminous', 'heavy duty', 'office power'],
    source: 'mock',
    unit: 'Unit',
  },
  {
    id: 'prod-inv-004',
    name: 'Microtek Solar Hybrid Inverter SS 1130 / 12V',
    slug: 'microtek-solar-hybrid-inverter-ss-1130',
    description: 'Dual-input hybrid solar inverter that optimizes solar panel energy intake before drawing from grid electricity, significantly reducing monthly bills.',
    category: 'Inverters',
    subcategory: 'Solar Hybrid Inverters',
    brand: 'Microtek',
    price: 9899,
    wholesalePrice: 8499,
    currency: 'INR',
    stockStatus: 'low_stock',
    availableQuantity: 8,
    minimumOrderQuantity: 1,
    tags: ['inverter', 'solar inverter', 'hybrid', 'microtek', 'green energy', 'under 10000'],
    source: 'mock',
    unit: 'Unit',
  },

  // ── Electrical Accessories ──
  {
    id: 'prod-elec-001',
    name: 'Havells Reo Modular Switch Pack (10A, 100 Units Carton)',
    slug: 'havells-reo-modular-switch-pack-100',
    description: 'Flame-retardant polycarbonate white modular switches with silver cadmium oxide contacts ensuring spark-free switching and 100,000 click life cycle.',
    category: 'Electrical Accessories',
    subcategory: 'Modular Switches',
    brand: 'Havells',
    price: 3800,
    wholesalePrice: 2950,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 150,
    minimumOrderQuantity: 2,
    tags: ['switch', 'modular switch', 'havells', 'reo', 'electricals', 'wiring'],
    source: 'mock',
    unit: 'Carton of 100 pcs',
  },
  {
    id: 'prod-elec-002',
    name: 'Polycab 2.5 sq mm FR PVC Insulated Copper Wire (90m Coil)',
    slug: 'polycab-2-5-sqmm-fr-copper-wire-90m',
    description: '99.97% electrolytic grade bright annealed copper conductor wire with flame-retardant (FR) PVC compound. ISI and CE certified for building installations.',
    category: 'Electrical Accessories',
    subcategory: 'Copper Wire Bundles',
    brand: 'Polycab',
    price: 2850,
    wholesalePrice: 2380,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 210,
    minimumOrderQuantity: 3,
    tags: ['wire', 'copper wire', 'polycab', 'electricals', 'cable', '90m'],
    source: 'mock',
    unit: '90 Meter Coil',
  },
  {
    id: 'prod-elec-003',
    name: 'Schneider Electric Acti9 32A Double Pole MCB (Pack of 10)',
    slug: 'schneider-acti9-32a-dp-mcb-pack',
    description: 'Type-C trip curve miniature circuit breaker with 10kA breaking capacity. Protects commercial air conditioners and heavy motors from overloads.',
    category: 'Electrical Accessories',
    subcategory: 'MCB & Isolators',
    brand: 'Schneider Electric',
    price: 5200,
    wholesalePrice: 4200,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 45,
    minimumOrderQuantity: 1,
    tags: ['mcb', 'circuit breaker', 'schneider', 'electrical accessories', 'protection'],
    source: 'mock',
    unit: 'Pack of 10 units',
  },

  // ── Bikes and Scooters ──
  {
    id: 'prod-bike-001',
    name: 'Hero Destini 125 Commercial Delivery Scooter',
    slug: 'hero-destini-125-commercial-edition',
    description: '125cc fuel-injected utility scooter fitted with heavy-duty rear luggage carrier and dual shock absorbers. Fuel economy of 50 kmpl in city delivery traffic.',
    category: 'Bikes and Scooters',
    subcategory: 'Cargo Delivery Two-Wheelers',
    brand: 'Hero MotoCorp',
    price: 84500,
    wholesalePrice: 76500,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 12,
    minimumOrderQuantity: 2,
    tags: ['scooter', 'hero', 'bike', 'delivery scooter', 'two wheeler', 'destini'],
    source: 'mock',
    unit: 'Vehicle',
  },
  {
    id: 'prod-bike-002',
    name: 'TVS XL100 Heavy Duty Utility Moped',
    slug: 'tvs-xl100-heavy-duty-moped',
    description: 'Legendary multi-purpose cargo workhorse with detachable pillion seat, front load platform, and fuel-efficient 4-stroke engine. Built for heavy market loads.',
    category: 'Bikes and Scooters',
    subcategory: 'Utility Bikes',
    brand: 'TVS',
    price: 49900,
    wholesalePrice: 44500,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 20,
    minimumOrderQuantity: 2,
    tags: ['tvs xl100', 'moped', 'cargo bike', 'two wheeler', 'heavy duty'],
    source: 'mock',
    unit: 'Vehicle',
  },
  {
    id: 'prod-bike-003',
    name: 'Honda Activa 6G Fleet Edition (Matte Steel)',
    slug: 'honda-activa-6g-fleet-edition',
    description: 'India’s most trusted 110cc scooter with eSP technology, telescopic suspension, and combi-brake system. Low maintenance operational fleet favorite.',
    category: 'Bikes and Scooters',
    subcategory: 'Commuter Scooters',
    brand: 'Honda',
    price: 79900,
    wholesalePrice: 73000,
    currency: 'INR',
    stockStatus: 'low_stock',
    availableQuantity: 5,
    minimumOrderQuantity: 2,
    tags: ['activa', 'honda activa', 'scooter', 'commuter', 'fleet scooter'],
    source: 'mock',
    unit: 'Vehicle',
  },

  // ── Electric Scooters ──
  {
    id: 'prod-ev-001',
    name: 'Ather 450X Gen 3 High-Performance EV Scooter',
    slug: 'ather-450x-gen-3-electric-scooter',
    description: '3.7 kWh lithium-ion smart electric scooter with TrueRange of 105 km, 7-inch touchscreen dashboard with Google Maps, and warp mode acceleration.',
    category: 'Electric Scooters',
    subcategory: 'High-Speed EV Scooters',
    brand: 'Ather Energy',
    price: 139900,
    wholesalePrice: 126000,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 15,
    minimumOrderQuantity: 1,
    tags: ['electric scooter', 'ev', 'ather', 'ather 450x', 'green vehicle'],
    source: 'mock',
    unit: 'Vehicle',
  },
  {
    id: 'prod-ev-002',
    name: 'Hero Electric Nyx HX Commercial Cargo EV',
    slug: 'hero-electric-nyx-hx-cargo-ev',
    description: 'Dual battery commercial electric scooter with 165 km certified range per charge. Foldable rear seat converts into spacious cargo luggage bed.',
    category: 'Electric Scooters',
    subcategory: 'Fleet Delivery EV',
    brand: 'Hero Electric',
    price: 78900,
    wholesalePrice: 69900,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 24,
    minimumOrderQuantity: 2,
    tags: ['electric scooter', 'hero electric', 'cargo ev', 'fleet', 'nyx', 'ev delivery'],
    source: 'mock',
    unit: 'Vehicle',
  },
  {
    id: 'prod-ev-003',
    name: 'Bounce Infinity E1+ Removable Battery EV',
    slug: 'bounce-infinity-e1-plus-ev',
    description: 'Electric scooter featuring swappable and portable battery packs that can be charged inside homes or offices using any regular 15A socket.',
    category: 'Electric Scooters',
    subcategory: 'Low-Speed Commuter EV',
    brand: 'Bounce',
    price: 64900,
    wholesalePrice: 57500,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 18,
    minimumOrderQuantity: 2,
    tags: ['electric scooter', 'bounce', 'swappable battery', 'ev', 'commuter'],
    source: 'mock',
    unit: 'Vehicle',
  },

  // ── Cycles ──
  {
    id: 'prod-cycle-001',
    name: 'Hero Royal Roadster 22-Inch Heavy Duty Cycle',
    slug: 'hero-royal-roadster-22-inch-heavy-duty',
    description: 'Rugged tubular steel frame single-speed bicycle with reinforced rear luggage carrier and center stand. Traditional workhorse for daily utility distribution.',
    category: 'Cycles',
    subcategory: 'Commercial Cargo Cycles',
    brand: 'Hero Cycles',
    price: 4950,
    wholesalePrice: 4100,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 70,
    minimumOrderQuantity: 5,
    tags: ['cycle', 'bicycle', 'hero cycle', 'roadster', 'heavy duty', 'cargo cycle'],
    source: 'mock',
    unit: 'Bicycle',
  },
  {
    id: 'prod-cycle-002',
    name: 'Hercules Roadeo Hardliner 26T 21-Speed MTB',
    slug: 'hercules-roadeo-hardliner-26t-mtb',
    description: 'Mountain terrain bike with front suspension fork, double-wall alloy rims, dual disc brakes, and Shimano 21-speed thumb shifters.',
    category: 'Cycles',
    subcategory: 'Mountain Terrain Bicycles',
    brand: 'Hercules',
    price: 13499,
    wholesalePrice: 11200,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 35,
    minimumOrderQuantity: 2,
    tags: ['cycle', 'mtb', 'hercules', 'bicycle', 'gear cycle', 'mountain bike'],
    source: 'mock',
    unit: 'Bicycle',
  },
  {
    id: 'prod-cycle-003',
    name: 'Firefox Mist 700C Hybrid Commuter City Bicycle',
    slug: 'firefox-mist-700c-hybrid-commuter',
    description: 'Lightweight alloy hybrid bike with 700c fast-rolling tyres and comfortable upright handlebar geometry. Built for smooth city commutes and fitness.',
    category: 'Cycles',
    subcategory: 'City Commuter Cycles',
    brand: 'Firefox',
    price: 18990,
    wholesalePrice: 15800,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 20,
    minimumOrderQuantity: 2,
    tags: ['cycle', 'firefox', 'hybrid bike', 'city bicycle', 'commuter'],
    source: 'mock',
    unit: 'Bicycle',
  },

  // ── Home and General Products ──
  {
    id: 'prod-012',
    name: 'Ergonomic Mesh Office Chair with Lumbar Support',
    slug: 'ergonomic-mesh-office-chair-lumbar-support',
    description: 'High-density breathable mesh back executive chair with adjustable 2D lumbar pad, multi-position tilt lock mechanism, and Class-4 gas lift rated to 135 kg.',
    category: 'Home and General Products',
    subcategory: 'Furniture & Seating',
    brand: 'ComfortPro',
    price: 12999,
    wholesalePrice: 9099,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 120,
    minimumOrderQuantity: 5,
    tags: ['chair', 'office chair', 'furniture', 'ergonomic chair', 'mesh chair', 'seating'],
    source: 'mock',
    unit: 'Piece',
  },
  {
    id: 'prod-home-002',
    name: 'Prestige Deluxe Stainless Steel 5-Piece Cookware Set',
    slug: 'prestige-deluxe-stainless-steel-cookware-set',
    description: 'Heavy gauge 3-ply sandwich bottom cookware set includes kadai with glass lid, frypan, and saucepan. Suitable for gas and induction hobs.',
    category: 'Home and General Products',
    subcategory: 'Cookware Sets',
    brand: 'Prestige',
    price: 4850,
    wholesalePrice: 3890,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 90,
    minimumOrderQuantity: 4,
    tags: ['cookware', 'prestige', 'kitchen', 'utensils', 'kadai', 'pan', 'steel'],
    source: 'mock',
    unit: 'Set',
  },
  {
    id: 'prod-home-003',
    name: 'Modular 5-Tier Heavy Steel Utility Shelving Rack',
    slug: 'modular-5-tier-heavy-steel-shelving-rack',
    description: 'Boltless powder-coated industrial steel rack supporting up to 150 kg per shelf. Versatile storage solution for retail shops, pantries, and warehouses.',
    category: 'Home and General Products',
    subcategory: 'Storage & Shelving',
    brand: 'Artisan Home',
    price: 6200,
    wholesalePrice: 4850,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 45,
    minimumOrderQuantity: 2,
    tags: ['rack', 'storage', 'shelving', 'steel rack', 'organizer', 'warehouse'],
    source: 'mock',
    unit: 'Unit',
  },
  {
    id: 'prod-001',
    name: 'Ceramic Table Vase — Matte White',
    slug: 'ceramic-table-vase-matte-white',
    description: 'Elegant matte white ceramic vase with a minimalist silhouette. Perfect for dried flowers or as a standalone tabletop decor accent. Height: 25cm.',
    category: 'Home and General Products',
    subcategory: 'Decor',
    brand: 'Artisan Home',
    price: 849,
    wholesalePrice: 595,
    currency: 'INR',
    stockStatus: 'in_stock',
    availableQuantity: 150,
    minimumOrderQuantity: 6,
    tags: ['ceramic', 'vase', 'white', 'minimalist', 'decor', 'home decor'],
    source: 'mock',
    unit: 'piece',
  },
];
